### ISSUE TITLE
Facebook Linking with Parse USer.

### ISSUE THREAD

**Issue by monishagarwal215** [ParsePlatform/Parse-SDK-Android#142]
Step 1: Created user via parse.In this case username is email and email column is email.

Step 2: Tried login via facebook with same email. In this case a new entry is made.

And then i check that with that email id facebook user exists or not

if exists then i delete a user and ask user to authenticate the email account via email and password.

and then again i ask user to link via code.

```java
ParseUser parseUser = ParseUser.getCurrentUser();
			if (!ParseFacebookUtils.isLinked(parseUser)) {
				ParseFacebookUtils.linkWithReadPermissionsInBackground(ParseUser.getCurrentUser(), ViewPagerActivity.this, permissions, new SaveCallback() {

					@Override
					public void done(ParseException e) {
						if (e == null) {
							updateParseUser(false, userProfile);
						} else {
							e.printStackTrace();
						}

					}
				});
			}
```
but this code it never links.

Exception comes

com.parse.ParseException: java.lang.IllegalArgumentException: Cannot save a ParseUser that is not authenticated.

I want to ask in link user method we have to pass the current user to be linked?

Please respond as it is very urgent.

**Comment by wangmengyan95** [comment]
Hi @monishagarwal215 , I tried your code snippet but I could not repo this problem.
Parse throw this exception because the user you tried to link is not the currentUser in Parse. 
Suppose when you call `linkWithReadPermissionsInBackground `, `Parse.getCurrentUser()` gives you userA, since link takes time, after the link finishes, when Parse try to save the link information of userA, the currentUser in Parse make becomes userB due to another user signup etc. In this case, we throw this exception. Since in your description, you mentioned you delete user and create new user, I suspect this is the source of you bug. So can you guarantee your `linkWithReadPermissionsInBackground` always happen after you sign up new user in your code?

**Comment by monishagarwal215** [comment]
Hi @wangmengyan95 when i added a line before this code System.out.println(ParseUser.getCurrentUser().isAuthenticated());
It gives true.
Should i mail you one sample code.
And as you said i am updating a user in done method callback of link, it always gives an exception.

Please help me out with sample code if possible.

Thanks.

Parse

**Comment by wangmengyan95** [comment]
@monishagarwal215 ，sure， you can upload your sample project to your github or share through dropbox, DON'T forget to remove your personal credential.

**Comment by monishagarwal215** [comment]
HI,

https://www.dropbox.com/s/ugollfmj1u9jdlu/main.rar?dl=0

I am providing you my whole project but i am not providing a libraray.

In that their is a ViewPagerActivity through which you will find and sign up process.

You ca sign up via email and by facebook also.

Step 1  is to sign up vial email

and then via facebook.

I have written my code of linking in onActivityResult.

I am also providing my apk  via drop box

https://www.dropbox.com/s/5jv4vynf0nwtmuh/LookAtMe%2819-9-2015%29.apk?dl=0

**Comment by monishagarwal215** [comment]
PLease look after into this.

Thanks a lot for your valuable time.

**Comment by monishagarwal215** [comment]
Thanks my issue is fixed...

**Comment by grantland** [comment]
For future reference, what actions did you take to resolve your issue?
