### ISSUE TITLE
Receive GCM push messages from an additional Sender ID

### ISSUE THREAD

**Issue by assizic** [ParsePlatform/Parse-SDK-Android#153]
Hi,

I'm configuring Parse to receive Push notification from another push provider (MixPanel). For that, I'm settings the gcm_sender_id meta as desribed in https://www.parse.com/docs/android/guide#push-notifications-setting-up-push:
<meta-data android:name="com.parse.push.gcm_sender_id"
           android:value="id:YOUR_SENDER_ID" />;

I see that push messages that are sent from the other push provider arrive to the device (see attached gcm diagnostics of a message send from MixPanel), but ParsePushBroadcastReceiver.onReceive is not called.

Anything other configuration is required to get this working?

Thanks,
Assaf

![gcm_diag](https://cloud.githubusercontent.com/assets/14328282/10057997/c043920c-624b-11e5-802e-1d6cf2dc3d5e.PNG)

**Comment by grantland** [comment]
I'm not familiar with MixPanel, but you can use your own `BroadcastReceiver` implementation instead of `com.parse.GcmBroadcastReceiver` to ensure that the push is in fact making it to your application.

If it isn't, the push isn't actually being delivered to the device or you've missing some crucial pieces when setting up Parse push.

In either case, this doesn't sound like it's related to the a bug or the source of the Parse SDK. If it turns out to be a issue with the Parse SDK, feel free to reopen this issue.

**Comment by vrandon** [comment]
Hi @assizic ,
Sorry for this (very) late answer, I have been running into the same issue for weeks now, and I just managed to solve it, so in case you're still having problems this might help you (http://stackoverflow.com/questions/31692757/android-parse-push-notification-and-new-gcm-generate-wrong-device-token-and-pars/31724197#31724197)

Explanation: when registering the other Gcm push provider, you are normally calling this:
               String token = instanceID.getToken(CommonUtils.SENDER_ID,
                       GoogleCloudMessaging.INSTANCE_ID_SCOPE, null); 

When later on you save your Parse Installation, your "deviceToken" changes (no idea why) and takes this new token value. Therefore you stop receiving Parse Push Notifications after that. So replace this line of code with the deviceToken from ParseInstallation and your good to go:
ParseInstallation.getCurrentInstallation().getString("deviceToken");

In the Parse Docs, when mentioning that Parse is compatible with other Push providers, it'd be nice to find this little trick somewhere!

Hope I've been helpful.

**Comment by assizic** [comment]
Thanks a lot @vrandon. We actually stopped using Parse push since it does not support high-priority GCM messages, but this will come handy if we ever go back to it.

Great day!

**Comment by bnham** [comment]
Parse registers for GCM for you. If you also register for GCM, the two registration ids will be associated with different GCM sender ids and either your mixpanel push or your parse push won't work.

If you use the gcm_sender_id meta value, then Parse will *additionally* register for GCM with the additional sender ID you provide at app start time. You can then access the device token associated with the additional sender id by calling ParseInstallation.getCurrentInstallation().getString("deviceToken"). But you shouldn't also register for push on your own using InstanceID. Just let Parse do the registration for you.

As for allowing MixPanel to send pushes to our GCM broadcast receiver, that isn't going to work because our BR expects pushes to come in via a particular format. You should just use a generic GCM broadcast receiver (or whatever MixPanel recommends) if you want to receive a push from MixPanel.
