### ISSUE TITLE
Why is GCMRegistrar not calling GoogleCloudMessaging.register?

### ISSUE THREAD

**Issue by cody1024d** [ParsePlatform/Parse-SDK-Android#16]
After looking through the source code, I see that you are not using the registration method provided by the GoogleCloudMessaging class, and are instead sending an intent manually.

I did a bit of digging, and the registration intent that you send seems to be similar to what the register method does.

Have you seen better results registering via this manual intent, versus calling the above method?  I am very curious to this because my personal apps, have had some very severe issues with GCM, and it's reliability.

    private void send() {
      Intent intent = new Intent(REGISTER_ACTION);
      intent.setPackage("com.google.android.gsf");
      intent.putExtra("sender", senderId);
      intent.putExtra("app", appIntent);

      ComponentName name = null;
      try {
        name = context.startService(intent);
      } catch (SecurityException exception) {
        // do nothing
      }

      if (name == null) {
        finish(null, "GSF_PACKAGE_NOT_AVAILABLE");
      }

      tries.incrementAndGet();

      PLog.v(TAG, "Sending GCM registration intent");
    }

**Comment by cody1024d** [comment]
The reason I'm asking is, I have found GCM to very unreliable, and are trying to find the cause.  Essentially, the server that sends pushes to Google's server get's a "Not Registered" response back all too frequently, as if the registration Id's on the devices themselves have gone stale.  

I was hoping this way of registering was a partial solution, or something, to that problem?

**Comment by grantland** [comment]
Good question! At the time we added support for GCM, the `Intent` we use was the recommended way to register GCM and documented by Google (which has since been taken down). There was a SDK available that did the same thing, but it is difficult to keep our integration simple when requiring additional dependencies during the days when Eclipse was the official IDE and there wasn't any real support for Maven.

Now, we have support for Maven with Gradle and Google Play Services is available through Maven with Android tools, so why don't we require Google Play Services now?

Mainly because it works and there's no real reason to change it, except for the sake of changing it. We wouldn't want to require it since it would add to add unwanted bloat to apps that don't utilize GCM and we wouldn't want to make it `provided` since it would be a "breaking change" to developers who do use it. There's also a slight benefit in not having developers who want GCM to include an extra line in their `dependencies`. Additionally, as you mentioned, there isn't much difference between our implementation and the one in Google Play Services.

If Google Play Services adds any functionality that we can't use via our implementation we might consider switching, but it'll need to outweigh it being a breaking change.

**Comment by cody1024d** [comment]
It seems they've since changed their suggested method of registering, even from the register method that I was referring to (they now suggest doing it via an InternalId API, and such).

Perhaps this isn't the right forum for it, but have you at all noticed inconsistencies with stale Push Id's?  Registering in the above manner?  I'm having a terrible time of it, right now haha

**Comment by bnham** [comment]
At the time we wrote this API, Google had two ways of informing us about a stale registration id: the server could respond with a "canonical id" at push time (at which point the server must update the stale registration id with the canonical id provided), or the Google can directly tell the client app that the registration is out-of-date by sending the com.google.android.c2dm.intent.REGISTRATION out of the blue to your app's GCM broadcast receiver. We have both server-side and client-side code to handle either of these cases.

If you're writing your own GCM implementation and are running into issues with it, it looks like this is a good group to start with: https://groups.google.com/forum/#!forum/android-gcm.

**Comment by cody1024d** [comment]
Thank you @bnham.  Closing this ticket as my original question has been answered.
