### ISSUE TITLE
User.getCurrentUser() returns null sometime

### ISSUE THREAD

**Issue by cyclewala** [ParsePlatform/Parse-SDK-Android#179]
Hi Team,

We are using Parse Android SDK 1.10.1
We have enable local storage (we have pinned the User object also)

We are able to signup the new user and they are getting logged in also in offline after relaunch.

But some times, We are getting User.getCurrentUser = null 
So due to this we have to relogin the user.

Even if we relogin programatically then also we are getting User.getCurrentUser = null.

Please help us to resolve this user.getCurrentUser = null issue.

This issue comes randomly even enabling local storage.

Tested Device : Samsung Galaxy Note 2, Moto G (3rd Generation)

**Comment by kaojohnny** [comment]
Some users reported same problem, seems not hard to reproduce but not reproducible in our lab . We also enable localStorage and using 1.10.1.

**Comment by martindykes** [comment]
Hi,

I am also seeing this issue.  
Quite simply, I call Parse.getCurrentUser() and it occasionally returns null.  I have seen this happen on Android 5.0 and and 4.1 and also when using local storage and not using local storage, I am using Parse library version 1.11.0.  It happens randomly in different parts of the application at any time.

I am building with the following android libraries:
compileSdkVersion 21
buildToolsVersion "21.1.1"
minSdkVersion 19
targetSdkVersion 21

What further information would help you?  I will do my best to provide it.

Martin

**Comment by grantland** [comment]
@martindykes Is this occurring during development or are you just seeing this on production clients?

If you're seeing this during development, it'd be great if you could provide us with a working sample project and describe an environment that it would reproduce on. The fact that you're observing this with both Local Datastore and without LDS makes this original report a bit vague.

My current hunch is that there's a failure reading the current user from disk [here](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/CachedCurrentUserController.java#L240), but since we're using `continueWith` as opposed to `onSuccess`, we won't know the failure without being able to reproduce this on a development device.

**Comment by kaojohnny** [comment]
I have some clients occurred same problem, how can we help? Though I can't reproduce this problem.

**Comment by muneeshseedoc** [comment]
Has someone found solution for it?
Parse saving current user object in json format on app folder in data, sometime it unable to read from there perhaps so return null.

**Comment by Shvet** [comment]
I am using kotlin for my current project (I have converted java code to kotlin of old working code), Now when i try to get user with  `getCurrentUser()` is always returns null, after login or registration done.
