### ISSUE TITLE
getDataInBackground ProgressCallback() not being called

### ISSUE THREAD

**Issue by indiandragon** [ParsePlatform/Parse-SDK-Android#186]
Parse Team,

Parse Version 1.10.3
I'm using getDataInBackground on Parse File object to download a audio file uploaded earlier but not able to get progress callback.

```
   downloadedAudio = (ParseFile)object.get("recordedAudioFile");

                    downloadedAudio.getDataInBackground(new GetDataCallback() {
                        public void done(byte[] data, ParseException e) {
                                if (e == null) {
                                   //Getting Called
                              }
                        else{
                      }
                  }
                    },new ProgressCallback(){
                        @Override
                        public void done(Integer percentDone) {
                         
                        // Note Getting Called anytime while downloading.
                          
                        }
                    });
```
Is progress callback for getDataInBackground working for anyone ?

**Comment by wangmengyan95** [comment]
Hi @indiandragon, I tried you code snippet and it worked fine in my device and emulator. One thing I want to remind you is since we keep a in memory cache for each ParseFile, if you have already had the data of this ParseFile in memory, we won't download the data again from network. In this situation, the ProgressCallback will not be called.
So in your case:
1. Can you reinstall or clear data of your app and download the ParseFile again to see if the ProgressCallback is triggered or not?
2. If it still does not work for you, it seems you can get the data of your ParseFile, have you verified the data is correct? Do you get any exceptions?
