### ISSUE TITLE
ParseCrashReporting not works due to stacktrace exceeded max size of 51200 bytes.

### ISSUE THREAD

**Issue by dekalo-stanislav** [ParsePlatform/Parse-SDK-Android#204]
ParseCrashReporting not works.

It seems because of next log:
W/CrashReporting( 2320): 63423-byte crash report 1445364348713-RuntimeException-90070.stacktrace exceeded max size of 51200 bytes; deleted

build:gradle
compile 'com.parse:parse-android:1.10.3'

called in Application::onCreate()
```
private void initParse() {
    ParseCrashReporting.enable(this);
    Parse.enableLocalDatastore(getApplicationContext());
    Parse.initialize(this, "***", "***");
    ParseUser.enableAutomaticUser();
    ParseUser.getCurrentUser().saveInBackground();
    Parse.setLogLevel(DEBUG ? Parse.LOG_LEVEL_VERBOSE : Parse.LOG_LEVEL_NONE);
    ParseInstallation.getCurrentInstallation().saveInBackground();
  }
```

```
E/CrashReporting( 2320): ParseCrashReporting caught a RuntimeException exception for ***. Building report.
E/CrashReporting( 2320): Handling exception for crash
E/CrashReporting( 2320): java.lang.RuntimeException: Test parse.
<stack trace here>
E/CrashReporting( 2320): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:304)
E/CrashReporting( 2320): 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
E/CrashReporting( 2320): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/CrashReporting( 2320): 	at android.os.Looper.loop(Looper.java:135)
E/CrashReporting( 2320): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/CrashReporting( 2320): 	at java.lang.reflect.Method.invoke(Native Method)
E/CrashReporting( 2320): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/CrashReporting( 2320): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/CrashReporting( 2320): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
D/CrashReporting( 2320): Generating report file for crash
D/CrashReporting( 2320): Retrieving logcat output...
D/CrashReporting( 2320): Retrieving logcat output...
D/CrashReporting( 2320): Retrieving logcat output...
V/CrashReporting( 2320): About to start ReportSenderWorker from #handleException
D/CrashReporting( 2320): #checkAndSendReports - start
D/CrashReporting( 2320): Looking for error files in /data/data/***/files/com.parse/cr/reports
D/CrashReporting( 2320): Loading file 1445364348713-RuntimeException-90070.stacktrace
W/CrashReporting( 2320): 63423-byte crash report 1445364348713-RuntimeException-90070.stacktrace exceeded max size of 51200 bytes; deleted
D/CrashReporting( 2320): #checkAndSendReports - finish
```

Please let me know if you need more information.

**Comment by stanleyw** [comment]
Thanks for your feedback.  We've decided to deprecate our Crash Reporting product, so we will not be fixing this limitation.  We sent out an email to active users of Parse Crash Reporting earlier today.  Here is a copy of that email:

--

Update to Parse Crash Reporting

Hi there,

At Parse, we're always working to improve your developer experience. Last December, we launched Parse Crash Reporting with the goals of recognizing, tracking, and ultimately resolving crashes in your app. 

In the time since, we've seen huge strides being made within the industry's native solutions. These native experiences have the advantage of being more tightly integrated into your build and release process, offering a more robust, streamlined, and frictionless development experience for you. 

The Parse Crash Reporting tool is now being deprecated in favor of these great native solutions. We will continue supporting Parse Crash Reporting until March 1, 2016.

Here's how you can smoothly switch from Parse Crash Reporting to Apple or Google's offerings:

- [Apple Docs] (https://developer.apple.com/library/watchos/documentation/IDEs/Conceptual/AppDistributionGuide/AnalyzingCrashReports/AnalyzingCrashReports.html)
- [Google Docs] (http://developer.android.com/distribute/googleplay/developer-console.html#reviews-reports)

We're constantly tackling new challenges to help you build better than ever before. Please reach out if you have any questions or concerns to community@parse.com.

The Parse Team
