### ISSUE TITLE
WhereDoesNotMatchKeyInQuery is overriden if used on the same key

### ISSUE THREAD

**Issue by Koridev** [ParsePlatform/Parse-SDK-Android#211]
When I use ParseQuery.whereDoesNotMatchKeyInQuery twice with the same "key" (first parameter) but different "keyInQuery" and "query", the first seems to be ignored, as if it was overriden.

My use case is:
I have object A with a field "user", Pointer to _User.
I have object B with fields "byUser" and "forUser", both Pointers to _User.
I want to get the list of objects A that have a "user" that is not referenced in an object B where one of "byUser" or "forUser" is my current user (it's a blocking behaviour, if user1 has blocked user2, none of them will receive the content of the other).

It gives something like this in code:

ParseQuery<ParseObject> aQuery = ParseQuery.getQuery("A");
aQuery.whereEqualTo("user", ParseUser.getCurrentUser());

ParseQuery<ParseObject> bForQuery = ParseQuery.getQuery("B");
        bForQuery.whereEqualTo("forUser", ParseUser.getCurrentUser());

ParseQuery<ParseObject> bByQuery = ParseQuery.getQuery("B");
        bByQuery.whereEqualTo("byUser", ParseUser.getCurrentUser());

aQuery.whereDoesNotMatchKeyInQuery("user", "forUser", bByQuery);
aQuery.whereDoesNotMatchKeyInQuery("user", "byUser", bForQuery);

--
The returned list is the same as if the first "whereDoesNotMatchKeyInQuery" was not called.

Thx

**Comment by grantland** [comment]
Unfortunately we don't allow multiple `whereDoesNotMatchKeyInQuery`s for the same key and right now our SDK uses the last condition: https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseQuery.java#L424

**Comment by Koridev** [comment]
Ok that's too bad...
Any idea on how should I proceed to achieve the same goal?
Will this feature be integrated any time soon?
Thx

**Comment by grantland** [comment]
We don't have any plans to support this functionality.

It seems like you could get away with it now by combining `bForQuery` and `bByQuery` with an `OR`.

**Comment by Koridev** [comment]
I don't think so since the keyInQuery is not the same. Or am I missing something?

**Comment by grantland** [comment]
You'll use the `OR`-ed query in `whereDoesNotMatchKeyInQuery`, which should be what you're trying to do.

```java
ParseQuery aQuery = ParseQuery.getQuery("A");
aQuery.whereEqualTo("user", ParseUser.getCurrentUser());

ParseQuery bForQuery = ParseQuery.getQuery("B");
bForQuery.whereEqualTo("forUser", ParseUser.getCurrentUser());

ParseQuery bByQuery = ParseQuery.getQuery("B");
bByQuery.whereEqualTo("byUser", ParseUser.getCurrentUser());

ParseQuery orQuery = ParseQuery.or(Arrays.asList(bForQuery, bByQuery));

aQuery.whereDoesNotMatchKeyInQuery("user", "forUser", orQuery);
```

**Comment by Koridev** [comment]
Yes but then the keyInQuery (second parameter of the last line) will only work for half the cases.
It should be 'doesNotMatchKeyInQuery' for 'forUser' AND 'byUser'.

**Comment by grantland** [comment]
Looking at this closer, your initial code doesn't really make sense. You're querying for objectAs who's "user" is yourself and not anyone that you've "blocked", but you'd never block yourself and then the query wouldn't return anything.

If you're trying to query objectAs who's "user" is just someone that you haven't blocked or hasn't blocked you, it might be worthwhile to simplify your problem a bit by converting your bidirectional "blocked" table (objectB) to be single direction by storing both X blocks Y and Y blocks X. This way you can have a single inner query.

I'll be closing this issue for now since you're original issue has been resolved. For further help regarding how to use Parse, I'd recommend checking out our [Google Groups](https://groups.google.com/forum/#!forum/parse-developers) or [Stack Overflow](http://stackoverflow.com/tags/parse.com).

Thanks!

**Comment by Koridev** [comment]
Oh indeed their shouldn't be the line "aQuery.whereEqualTo("user", ParseUser.getCurrentUser());"
It actually is "whereNotEqualTo", as it is in my original code, and it's not event relevant for this point.

But that does not change the fact that I can't filter by removing both 'A's where the user is not someone I have blocked nor someone that has blocked me in a single request with the current SDK.

Thanks anyway, you did answer my original question.
