### ISSUE TITLE
quickstart native Install the SDK

### ISSUE THREAD

**Issue by yonifreedmn** [ParsePlatform/Parse-SDK-Android#219]
dependencies {
    compile 'com.parse.bolts:bolts-android:1.+'
    compile 'com.parse:parse-android:1.+'
}

gives a duplicate error when compiling, 
when i removed them and returned to version 1.10.1 it worked

**Comment by wangmengyan95** [comment]
Hi @yonifreedmn, I test with our empty starter project with those dependencies and it works fine. So in your case, could you provide the following information:
1. Your module's dependencies
2. The exception of gradle
Make sure you do not include the Parse jar file if you also use Parse from maven, most of the duplicate errors are caused by this.

**Comment by yonifreedmn** [comment]
"Make sure you do not include the Parse jar file if you also use Parse from maven, most of the duplicate errors are caused by this."

that worked, I delete the JAR from the lib directory.
thx
