### ISSUE TITLE
Delivery report not showing complete data for all users

### ISSUE THREAD

**Issue by abhinav-koppula** [ParsePlatform/Parse-SDK-Android#220]
The Parse dashboard shows the following data for a particular push:

Delivery Report:
SUCCESSFUL DELIVERIES
5902

PPNS - OUTDATED DEVICE
17

GCM - NOT REGISTERED
718

GCM - GCM DEVICE TOKEN IS EMPTY
45

However, the push was sent to 7819 users. Can you please explain why the data for ~1K users is missing. Was the push successfully sent to those ~1K users?

**Comment by wangmengyan95** [comment]
Hi @abhinav-koppula, the successful deliveries number is the number of push notifications we actually send. I am curious how do you know the push was sent to 7819 users? If it is just the number of users or installations it is not accurate since not all installations are valid for us to target.

**Comment by abhinav-koppula** [comment]
Hi @wangmengyan95 , thanks for replying. Yes, I was assuming that total number of pushes sent would be equal to the total number of installations. Thanks for clarifying this. However, can you please explain why the total number of installations are not equal to the number of push notifications Parse actually sends? Does this mean that multiple installation objects correspond to the same device and hence Parse only sends one notification for that device? If so, is there any way to prevent multiple installation objects to be created for the same device?

Thanks a lot

**Comment by wangmengyan95** [comment]
Hi @abhinav-koppula,
1. Not all installations are valid installations. We use google GCM to send push notification and GCM needs a registration id to identify a device. So a valid installation must have the registration id which is stored under the deviceToken field. Sometimes the registration process may fail due to network issues or GCM issues, in those cases, the installations may become invalid and we can not target those devices. Thus,  the total number of installations are not equal to the number of push notifications Parse sends.
2. If users manually clear the app's cache or reinstall the app, we may create multiple installation objects for the same app of the same device. However, we do deduplicate push notifications in our client side and we delete this kind of installations in our backend we you send push notifications, so you do not need to concern this issue too much.
