### ISSUE TITLE
Vulnerability application keys get caught in packet capture.

### ISSUE THREAD

**Issue by 99digitechapps** [ParsePlatform/Parse-SDK-Android#230]
Please work on it! 
![photo_2015-11-02_19-12-18](https://cloud.githubusercontent.com/assets/15515930/10884444/22b6fb4c-819e-11e5-8c07-27c349501009.jpg)

**Comment by wangmengyan95** [comment]
Hi @99digitechapps, the app id and client key are supposed to be exposed to the public. In order to prevent others from using or get accessing to your parse app, make sure you set the proper ACLs or use cloudcode befoareSave hooks on your objects/classes to authorize proper users and after that your data will be safe and secured. The app id and key combination will just authenticate your app, rather than authorize it (authorization is handled by ACLs).

**Comment by grantland** [comment]
In addition, the traffic you're looking at is over HTTPS which is encrypted. The only reason you can see the information is because you've rooted your device or you've trusted a third party certificate, so a third party would not be able to man-in-the-middle your requests unless you've explicitly gave them permission.

**Comment by 99digitechapps** [comment]
@wangmengyan95 Hey! thanks for the suggestions on ACLs i will try it. But help me with a guide if you can. I got your concept of authorization. Thanks!
@grantland You are right i had to add a 3rd party certificate. But i didn't root my device. I used it to test if any info is leaking out. But thanks alot for your reply. That really helped.

**Comment by grantland** [comment]
Here's our guide on security: https://parse.com/docs/android/guide#security

Regarding adding the 3rd party certificate, only you and the service you're using has access to this data since you approved their certificate. No other parties will have access to the encrypted data over the wire.
