### ISSUE TITLE
Missing ParseCrashReporting

### ISSUE THREAD

**Issue by alanblins** [ParsePlatform/Parse-SDK-Android#247]
ParseCrashReporting-*.jar is missing from repository.

**Comment by stanleyw** [comment]
Thanks for your feedback, we've decided to deprecate our Crash Reporting product, so the Crash Reporting jar will not be in this repository.  We sent out an email to active users of Parse Crash Reporting earlier today.  Here is a copy of that email:

--

Update to Parse Crash Reporting

Hi there,

At Parse, we're always working to improve your developer experience. Last December, we launched Parse Crash Reporting with the goals of recognizing, tracking, and ultimately resolving crashes in your app. 

In the time since, we've seen huge strides being made within the industry's native solutions. These native experiences have the advantage of being more tightly integrated into your build and release process, offering a more robust, streamlined, and frictionless development experience for you. 

The Parse Crash Reporting tool is now being deprecated in favor of these great native solutions. We will continue supporting Parse Crash Reporting until March 1, 2016.

Here's how you can smoothly switch from Parse Crash Reporting to Apple or Google's offerings:

- [Apple Docs] (https://developer.apple.com/library/watchos/documentation/IDEs/Conceptual/AppDistributionGuide/AnalyzingCrashReports/AnalyzingCrashReports.html)
- [Google Docs] (http://developer.android.com/distribute/googleplay/developer-console.html#reviews-reports)

We're constantly tackling new challenges to help you build better than ever before. Please reach out if you have any questions or concerns to community@parse.com.

The Parse Team
