### ISSUE TITLE
Notifications received from uninstalled development app

### ISSUE THREAD

**Issue by derrickleeqanvast** [ParsePlatform/Parse-SDK-Android#255]
I have two parse projects one for development and one for production using the same account.
But I'm receiving push notifications from my development app when I'm using the production app.
Both projects are using different app ids and client keys. 
Please help thank you.

The steps to reproduce:

- Run development app [Parse v.1.10.3]
- In the app, I've subscribed to the ```general``` channel
- Tried pushing through the development project dashboard filtered by ```general``` channel and ```android``` only. Its still okay here, I'm receiving once. [JSON format]
- Uninstall the development app
- Install the production app in the Google Play Store [Parse v.1.10.2]
- In the app, subscribed to the ```general``` channel
- Tried pushing through the development project dashboard filtered by ```general``` channel and ```android``` only, i'm still receiving the notifications. [JSON format]
- Tried pushing again I'm still receiving it.

**Comment by wangmengyan95** [comment]
Hi @derrickleeqanvast, Parse actually uses google could message(GCM) to send push notifications to your device. The problem you mention is actually a limitation of GCM. GCM uses registrationId(deviceToken in your ParseInstallation) to send push notifications to your device. When your device gets the push notification, it will deliver the push notification to the app based on appId(appIdentifier in your ParseInstallation).
When you delete the an app, GCM will not invalid the registrationId immediately. It will still try to send push notifications to the registrationId if it gets request. So in your case, even you delete the development app, when you use the development parse app to send push notifications, GCM will still try to send push notifications to the old registrationId(Ideally this should not happen). Since your production app still uses the same appId, your production app can get the notifications. This issue only happens if your different apps share the same appIdentifier(which is not recommended by google).

**Comment by wangmengyan95** [comment]
Hi @derrickleeqanvast, Parse actually uses google could message(GCM) to send push notifications to your device. The problem you mention is actually a limitation of GCM. GCM uses registrationId(deviceToken in your ParseInstallation) to send push notifications to your device. When your device gets the push notification, it will deliver the push notification to the app based on appId(appIdentifier in your ParseInstallation).
When you delete the an app, GCM will not invalid the registrationId immediately. It will still try to send push notifications to the registrationId if it gets request. So in your case, even you delete the development app, when you use the development parse app to send push notifications, GCM will still try to send push notifications to the old registrationId(Ideally this should not happen). Since your production app still uses the same appId, your production app can get the notifications. This issue only happens if your different apps share the same appIdentifier(which is not recommended by google).

**Comment by derrickleeqanvast** [comment]
Wait app id do you mean parse app id or gcm app id? Because both projects are using different parse application ids.

**Comment by wangmengyan95** [comment]
The appId I mean is the gcm app id. It is the appIdentifier in your ParseInstallation. Normally it is the package name of your app.

**Comment by derrickleeqanvast** [comment]
alright thanks
