### ISSUE TITLE
ParseFacebookUtils.isLinked(user) returning false after executing query with 'user' key included

### ISSUE THREAD

**Issue by SobanMahmood** [ParsePlatform/Parse-SDK-Android#269]
I have Parse object named 'Activity' on back end, which has a pointer to 'User' object.
In my android app, after logging in or linking through ParseFacebookUtils, if I made a parse query on 'Activity' and include key 'user' to that query for fetching users' details, then ParseFacebookUtils.isLinked(ParseUser.getCurrentUser()) starts returning false after that query. However if I kill android app and relaunch it, then ParseFacebookUtils.isLinked(ParseUser.getCurrentUser()) starts returning true again. It seems as for some reason some cached data is getting affected after making query with 'user' key included. This does not happen if query is made without including key 'user'.
This happens if at least one of the fetched 'Activities' has current logged in user set as the 'user' pointer.

**Comment by SobanMahmood** [comment]
Sdks I am using are as following:
com.facebook.android:facebook-android-sdk:4.6.0
com.parse:parsefacebookutils-v4-android:1.10.3@aar
com.parse:parse-android:1.10.3

**Comment by wangmengyan95** [comment]
Hi @SobanMahmood, do you use the local datastore in your app?

**Comment by SobanMahmood** [comment]
Hi @wangmengyan95 , thanks for the response.
Yeah, I am using local datastore in my app.
Please let me know if any other info is required.

**Comment by wangmengyan95** [comment]
Hi @SobanMahmood, another question I want to know is whether you use the local datastore all the time? All the time means when you log in or link with Facebook and do the query, the local datastore is always enabled. I assume this is your case, but I just want to make sure, since we have some migration step when you first enable local datastore. I want to narrow down the scope. Thanks.

**Comment by SobanMahmood** [comment]
@wangmengyan95 yeah, Local datastore is always enabled in my case. In fact it is enabled at start of the application in overridden method onCreate() of extended Application class.

**Comment by wangmengyan95** [comment]
Hi @SobanMahmood, I can repo this issue. It seems a valid bug. I will try to figure out why this happen. Thanks for opening this issue!

**Comment by wangmengyan95** [comment]
I find the case of this issue. When you login, we keep a in-memory and in-disk currentUser object. When you query a ParseUser, the server will not include the authData for security reason. For you case, if you include the user key, when we get the response and try to decode it, we will try to use the incomplete data to rebuild the user. If the user is the currentUser, we will use the new-build user which is incomplete to overwrite the in-memory currentUser. That's why the ParseFacebookUtils.isLinked(ParseUser.getCurrentUser()) will return false. However, since we do not change the in-disk currentUser, when you relaunch the app, we read the currentUser from disk and ParseFacebookUtils.isLinked(ParseUser.getCurrentUser()) return the true result.
My current solutation for this is to change the third parameter [here](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseDecoder.java#L125), since if the Object is a _User object, we can not guarantee it is complete. But I am not 100% sure it is safe to do this. Any thoughts? @grantland

**Comment by SobanMahmood** [comment]
Hi @wangmengyan95, thanks for the supprot. I hope this issue will get fixed in next release. Until then, is there any work around possible with the current version?

**Comment by wangmengyan95** [comment]
Hi @SobanMahmood, one possible solution is after you do this kind of query, you manually fetch the currentUser by calling `ParseUser.getCurrentUser().fetchInBackground();` or `ParseUser.getCurrentUser().fetch();` (depends on whether you want to use the async or sync version). Then the currentUser should contain the authData.

**Comment by grantland** [comment]
@wangmengyan95 we'd probably want to add `authData` to the checks here: https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseUser.java#L506

**Comment by SobanMahmood** [comment]
Thanks @wangmengyan95 for the work around, that seems simple, I hope this will do the trick.
