### ISSUE TITLE
ParseQueryAdapter with RecyclerView

### ISSUE THREAD

**Issue by msrowley** [ParsePlatform/Parse-SDK-Android#27]
As far as I searched ParseQueryAdapter is only compatible with Listview, but there is no official way to use it with RecyclerView. Will there be a tutorial or a new adapter that will be compatible with recycler view??

**Comment by wangmengyan95** [comment]
@msrowley I am sorry but there is no short-term plan for this feature right now. Since we move `ParseQueryAdapter` to [ParseUI](https://github.com/ParsePlatform/ParseUI-Android), so I will close this issue. It would be great you can reopen it in [ParseUI](https://github.com/ParsePlatform/ParseUI-Android).
