### ISSUE TITLE
Parse Cursor?

### ISSUE THREAD

**Issue by ajfclark** [ParsePlatform/Parse-SDK-Android#276]
Something I was very surprised not to find in the Parse Android SDK was a Cursor implementation. I know there's an Adapter in the UI package, but Cursor is a fairly standard data access class that drops into all kinds of Adapters. For the project I recently completed, I put together a very simple ParseCursor to hand to my RecyclerView.Adapters and so on. While it didn't take long, it did feel like it was something missing from the Parse SDK.

Are there plans for a ParseCursor to be included?

**Comment by grantland** [comment]
We don't have any plans to implement a `ParseCursor`. Could you describe the functionality of your implementation and it's use cases? I don't really see any default `RecyclerView.Adapter` implementations in AOSP that accept `Cursor`s.

**Comment by ajfclark** [comment]
That may be, but Android devs are used to working with cursors for their data access. ContentProviders return them, the Loader interface uses them, SimpleCursorAdapter and CursorAdapters take them, etc.

When converting from a different data backend to parse (either within a project or when starting a new one) it'd be far easier and cleaner if Cursors were there (and a suitable Loader too actually).

**Comment by grantland** [comment]
It seems like implementing `ParseCursor` is a roundabout way to support `Loader` functionality. In your case, wouldn't it be more useful to have a `ParseQueryLoader`?

I'll admit that there are some similarities between `Cursor`s and `ParseQuery` results, but `Cursor`s are a database abstraction and implementing a `ParseQueryCursor` seems like shoving a square peg in a round hole.

And in either case, this seems much more suited to be part of [ParseUI-Android](https://github.com/ParsePlatform/ParseUI-Android) since this repo is strictly for persisting and retrieving data with Parse while ParseUI-Android contains our UI bindings and functionality.

**Comment by ajfclark** [comment]
Cursor is also the building block required when implementing a ContentProvider. Cursors, Loaders and ContentProviders all hang together nicely to create a fairly simple and uniform way to access data. It'd make getting data from Parse the same as getting data from a database or the contacts or whatever. While I understand it might be a bit much to implement a generic ParseContentProvider, I was disappointed when I started looking at the Parse Android SDK that it didn't leverage the classes already provided for data access. It felt more like a generic Java SDK than an Android SDK.

I'm also not quite sure how they fit into the UI library. They are pure data abstractions to don't interact with the interface?

**Comment by grantland** [comment]
Could you describe what `ParseCursor` would solve in this case? I can really only see two implementations that each have their own problems:

1. `ParseCursor` wraps a `ParseQuery#find()` result set.
  * Pros
    * You can bind `ParseQuery` results to `ListView`/`RecyclerView` using `Cursor` based adapters.
  * Cons
    * This doesn't really provide any additional functionality that isn't already provided with the current `List` result type. Both are a static result that can be iterated. Why not just use `ArrayAdapter` or something similar?
2. `ParseCursor` wraps `ParseQuery` that asynchronously loads results.
  * Pros
    * Abstracts asynchronous loading of results.
    * `ParseQuery` results can be retained across `Activity` configuration changes.
  * Cons
    * `Cursor` API doesn't support dynamic result sets such, which is needed for paging.
    * `Loader`s don't support failures, so what do we do with failures?
    * This doesn't really provide any additional functionality that isn't already provided with the current `List` result type. Both are a static result that can be iterated. Why not use `AsyncTaskLoader`?

**Comment by ajfclark** [comment]
I guess I'm looking at things from a different perspective. When I first saw there was an Android API I thought it'd make Parse appear as close as possible to a "normal" datasource. I think it'd be great if there was just a ContentProvider that you gave a little configuration to and could then access using the normal ContentResolver query() framework via a Cursor implementation. There'd be no learning curve to use Parse and/or migrate a project from a local SQLite implementation to a cloud based one. 

As it currently stands, you need to learn a whole new set of Parse API calls, different async callback Interfaces, etc that all kind of mirror stuff that's already available in the Android framework but Parse does it all slightly differently. As you point out, a Cursor is almost exactly the same at the List returned by ParseQuery - so why didn't ParseQuery return a Cursor in the first place? Likewise, there's FindCallbacks and GetCallbacks for handling the async return from a ParseQuery - Why didn't they fit into the Loader interface in the first place? I'd be willing to sacrifice some of the Parse specific functionality to have a library that just dropped in.

I think we can write this off that I had a very different expectation of what the Parse-SDK-Android would provide to developers when I first picked it up.

**Comment by grantland** [comment]
It seems like you're coming from a very different background than most Android developers we've encountered. You seem to have a lot of experience with `ContentResolver`s and SQLite on Android, which is something most developers either don't have a good understanding of or completely avoid to the amount of work required to implement them correctly. In addition, they generally prefer more portable solutions that can be used anywhere rather than locking themselves into using `Loader`s and other database abstractions for non-database related work.

> As you point out, a Cursor is almost exactly the same at the List returned by ParseQuery - so why didn't ParseQuery return a Cursor in the first place?

Like I explained earlier, `Cursor`s are an abstraction for database related constructs which can possibly block the main thread while iterating the results since the entire window isn't loaded into memory by default. `List`, on the other hand, is a more generic construct that is applicable to anything in Java and, by contract with the `List` interface, contains all it's items in memory already and doesn't have to block the main thread. It'd also be extremely inefficient for each `ParseQuery` result to be fetched from the network like a how a `Cursor` operates.

> Likewise, there's FindCallbacks and GetCallbacks for handling the async return from a ParseQuery - Why didn't they fit into the Loader interface in the first place?

1. Parse's API was designed before `Loader`s existed. We support android-9 and `Loader` was introduced in android-11.
2. The `Loader` interface doesn't adapt well to non-`ContentResolver` situations--It doesn't provide an API for failures, changing result sets such as a paging `ParseQuery`, etc.
3. `ParseQuery` supports both promise and callback based asynchronous work via `Task` and `FindCallback`/`GetCallback`. These are much more portable solution than tying it directly to a poorly designed API such as `Loader`.
