### ISSUE TITLE
Newly created columns and data cannot be retrieved

### ISSUE THREAD

**Issue by jasonlosito** [ParsePlatform/Parse-SDK-Android#293]
I have added some new columns and data via the Dashboard and shows that is has been saved. However, I can't retrieved them in the app I am currently working on. The old columns and data, works fine.

**Comment by wangmengyan95** [comment]
Hi @jasonlosito, we only use this repo to track Parse Android SDK issues. Since the SDK still works fine with your old data. It seems a backend or parse dashboard issue to me. We continue to use Facebook bug reports tool to track those issues, please file a bug here https://www.parse.com/help. Thanks.
