### ISSUE TITLE
Logout function doesn't work

### ISSUE THREAD

**Issue by ray1984** [ParsePlatform/Parse-SDK-Android#315]
On logout from my application I do ```ParseUser.logOut();``` but notifications still are send on device. Also I tried ```ParseInstallation.getCurrentInstallation().deleteInBackground()``` but it doesn't work too.

**Comment by wangmengyan95** [comment]
Hi @ray1984 
1. `ParseUser.logOut()` will not help since notification is only related to `ParseInstallation` not `ParseUser`.
2. Even you delete `currentInstallation` when you open your app, our SDK will try to register a new `ParseInstallation` for the device.
The normal way to exclude some devices is to register different devices to different channels and use query in push dashboard to exclude some devices.

**Comment by ray1984** [comment]
But what can I do with existing installation? I created 3 installation, logout doesn't work, and now I receive notifications from all installation in on device

**Comment by wangmengyan95** [comment]
Hi @ray1984, you can
1. Delete the `currentInstallation` manually.
2. Call `Parse.getCurrentInstallation()` to get a new `currentInstallation`
3. Set some channels to the `getCurrentInstallation`
4. Use query to send push notifications.

**Comment by grantland** [comment]
> Even you delete currentInstallation when you open your app, our SDK will try to register a new ParseInstallation for the device.

This is incorrect. DO NOT DELETE INSTALLATIONS FROM PARSE. The client will get into a unusable state if this happens since it'll have an installation with an objectId that doesn't exist and won't be able to update it. The only way to fix this state would be for the user to uninstall and reinstall the application.

> But what can I do with existing installation? I created 3 installation, logout doesn't work, and now I receive notifications from all installation in on device

Like @wangmengyan95 said, `ParseInstallation` instances are not tied to `ParseUser`, so `#logout()` will not affect push notifications. If you want pushes to stop sending to a device that the user logs out from, you'll need to undo whatever you've done to link the `ParseInstallation` to the `ParseUser` in the first place.

I'll be closing this issue since it's not a bug and I recommend referring to Google Groups or Stack Overflow if you still require help using Parse.
