### ISSUE TITLE
Add consumer proguard rules

### ISSUE THREAD

**Issue by thuytrinh** [ParsePlatform/Parse-SDK-Android#343]
https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/ParseStarterProject/proguard-rules.pro should be included in Parse project as [a consumer proguard file](https://github.com/googlesamples/android-testing-templates/blob/master/AndroidTestingBlueprint/module-android-library/proguard-consumer-rules.pro#L1). A benefit is that projects that depend on Parse wouldn't need to bundle a dedicated proguard file for it. So that would save lots of time and effort. [Latest Play services has done the same thing](https://developers.google.com/android/guides/setup).

Wdyt?

**Comment by grantland** [comment]
That sounds awesome! We'd be more than happy to accept a PR that introduces this. 

Would you happen to know how it interacts with existing proguard rules with the same exact parameters? Wondering since we wouldn't want to break users who have these rules already as well as still publishing these rules for those using the JAR.
