### ISSUE TITLE
Use my GCMSenderId

### ISSUE THREAD

**Issue by gdoussot** [ParsePlatform/Parse-SDK-Android#39]
Hello, I want to use my own GCMSenderID.
When I register to Parse in my application OnCreate :

@Override
    public void onCreate() {
        super.onCreate();
...
        Parse.initialize(this, getParseAppId(), getParseClientKey());
        ParseInstallation.getCurrentInstallation().saveInBackground();
...

And in my Manifest :

...
<meta-data android:name="com.parse.push.gcm_sender_id"
            android:value="id:<MY_GCM_SENDER_ID>" />;
...

When I launch my application I can see in Parse console a new row, with a strange deviceToken :

|ID|1|:ftMuTQhPEUI:<A_TOKEN_ID_INVALID_WITH_MY_GCM_SENDER_ID>

And an (undefined) GCMSenderId.

My app in Parse is well configured with GCM informations.

**Comment by grantland** [comment]
So there are two parts to setting up your own GCM Sender ID:

1. Being able to receive pushes from an alternative GCM Sender ID. **This is generally desired by developers who want their applications to receive pushes from both Parse and their own push infrastructure.** For this, you need to add a `meta-data` tag in your `AndroidManifest.xml` with one or more GCM Sender IDs you'd like to receive from:

    ```xml
    <meta-data android:name="com.parse.push.gcm_sender_id"
               android:value="id:YOUR_SENDER_ID_1,YOUR_SENDER_ID_2,YOUR_SENDER_ID_3" />;
    ```

2. Being able to send pushes from Parse with an alternative GCM Sender ID. **This is generally desired by developers who have migrated their existing push infrastructure to Parse and need to be able to send pushes to applications with old GCM Sender IDs.** For this, you need to enter your GCM Push Credentials in your application's Push settings at http://parse.com and set `GCMSenderId` on `ParseInstallation` instances that require the designated `GCMSenderId` to receive pushes.

What are you currently trying to accomplish?

**Comment by Jinoooo** [comment]
I have the same problem.  I am trying to use only gcm push.  I added GCMSenderId & API Key to Parse Setting, plus added <meta-data> with one SenderId in android manifest file.  The installation object in parse is lacking the GCMSenderID, and although I can send the push via Parse Dashboard, it won't be received on device.  
When I add the GCMSenderId in Installation Object manually, I receive the PN on device.
Note:  My app is new and I only want to handle the push using Parse/GCM.

**Comment by grantland** [comment]
@Jinoooo Could you clarify your issue? It sounds like you've solved your problem and are receiving pushes with your custom GCM Sender ID.

**Comment by Jinoooo** [comment]
Yes, everything is working fine, although I had to hack the installation object using beforeSave hook in ParseCloud to inject my GCMSenderID for android.

It seems parseSDK is adding deviceType=android, deviceToken=xyz and somehow in the Cloud pushType=gcm will be added (I noticed in beforeSave hook).  I added the following as a child of <application> in androidManifest file, expecting ParseSDK to pick it up, but it is not happening and that seems to be a bug.
<meta-data android:name="com.parse.push.gcm_sender_id" android:value="id:MY_SENDER_ID" />

I am building a hybridApp and had to use ParsePlugin to build the installationObj, as Parse-JS SDK is not able to handle the Installation Obj.  I also tried doing the same using Parse Rest API, but couldn't find any correct/complete documentation on the Parse side to identify what fields should be populated by client to use GCM as a provider.

I am using ParseSDK 1.9.1 and even tried 1.10.1 without any success.  So I say still the bug is there somewhere, or I am missing something ?!

**Comment by grantland** [comment]
@Jinoooo The situation you're describing is working as intended. If you could refer to the second point in my post [above](https://github.com/ParsePlatform/Parse-SDK-Android/issues/39#issuecomment-133077876), I state that you must set `GCMSenderId` in your `ParseInstallation` for devices that require that GCM Sender ID to receive pushes. In addition, **this is generally desired by developers who have migrated their existing push infrastructure to Parse and need to be able to send pushes to applications with old GCM Sender IDs**.

**Comment by Jinoooo** [comment]
I tried your first point before. The approach didn't work for me and GCMSendId was undefined in the cloud (maybe is not necessary in this case?)

Here is from the link you provided (explaining your first point):

"The Parse Android SDK chooses a reasonable default configuration so that you do not have to worry about GCM registration ids, sender ids, or API keys. In particular, the SDK will automatically register your app for push at startup time using Parse's sender ID (1076345567071) and will store the resulting registration ID in the deviceToken field of the app's current ParseInstallation."
"However, as an advanced feature for developers that want to send pushes from multiple push providers, Parse allows you to optionally register your app for pushes with additional GCM sender IDs. To do this, specify the additional GCM sender ID with the following <meta-data> tag as a child of the <application> element in your app's AndroidManifest.xml:
meta-data android:name="com.parse.push.gcm_sender_id  android:value="id:YOUR_SENDER_ID" 

And that is what I followed.  It didn't work.  Maybe you can explain the following:
1 - where/when pushType=gcm will be injected into installation object?
2 - Should we expect GCMSenderID to be part of installation if "com.parse.push.gcm_sender_id" has been set in the androidManifestFile (for point one)? if not, then?
3 - Currently I am experiencing delays (1-2 min) to receive push notification on device.  Is that because parse relaying the message to GCM server, (it is not happening for my APN based devices which is similar)

Thanks for taking the time to look into this.

Cheers,
Mike

**Comment by grantland** [comment]
@Jinoooo The first point only describes setting up the Parse SDK to **receive pushes from Parse and their own infrastructure**. In this case, Parse would send via our own default GCM Sender ID (assuming you haven't modified it) and your own infrastructure would send pushes with your custom GCM Sender ID. If you also want Parse to send via your own GCM Sender ID, you need to also complete the second part.

> 1 - where/when pushType=gcm will be injected into installation object?

These are defaults set by the SDK.

> 2 - Should we expect GCMSenderID to be part of installation if "com.parse.push.gcm_sender_id" has been set in the androidManifestFile (for point one)? if not, then?

As stated in part 2 of my original comment, you need to set that on your own. Please re-read the reasons for each part to ensure you're doing these things for the right reasons.

> 3 - Currently I am experiencing delays (1-2 min) to receive push notification on device. Is that because parse relaying the message to GCM server, (it is not happening for my APN based devices which is similar)

This is not a valid question for this project, but more for Google Groups or Stack Overflow. Please refer to our [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md) for more information.

**Comment by Jinoooo** [comment]
pushType: This field is reserved for directing Parse to the push delivery network to be used. If the device is registered to receive pushes via GCM, this field will be marked "gcm". If this device is not using GCM, and is using Parse's push notification service, it will be blank (readonly).
"These are defaults set by the SDK." 

Question:  How to identify a device is registered  to receive pushes via GCM (on the client side) after calling Parse.initialize(app, appId, clientKey)?   I am not setting anywhere in the code the pushType. 
Please note I am setting the GCMSenderId in the cloud, so still wondering how SDK knows the type would be 'gcm'?

**Comment by Jinoooo** [comment]
update:
for point#2 when I remove the GCMSenderId from manifest file, the deviceToken will be null in installation object.  Is that a normal behaviour?

**Comment by gdoussot** [comment]
Finally, we use another solution. You can close this topic.
Just to understand the trouble : we want to store all users token registered with owner GCM sender to have no dependance with a tierce solution.

Thank you for your time.

**Comment by SamCallejo** [comment]
@grantland 
Per your comment " set GCMSenderId on ParseInstallation instances ".

How do you do this.  I don't see a GCMSenderId property or method to set that property in https://parseplatform.github.io/Parse-SDK-dotNET/api/html/T_Parse_ParseInstallation.htm
