### ISSUE TITLE
How about real REST-full calls ? ...

### ISSUE THREAD

**Issue by adadgio** [ParsePlatform/Parse-SDK-Android#408]
How about REST-full calls in the SDK ?

Currently a lot of calls are made using POST requests with an additional parameter in the request

`"_method": "GET`

The parse-server support CRUD operations (and thats how its specified in he REST docs). So how about really beeing restfull ? Example: Parse Queries are made using POST with the "_GET" parameter, as well as GET user, GET parse Object, etc...

Some people might use a different backend with the Parse SDKs.

**Comment by nlutsenko** [comment]
There is a good reason for it - RFC has a limit on URL length.
If you are doing a query - turns out that if you have a lot of conditions, there is a good chance that the request is going to fail, since you specified too much.

To work around this issue without breaking the REST API format that we have - this flow exists and being used.

cc @grantland @richardjrossiii

**Comment by nlutsenko** [comment]
This said, if you find the methods where we are abusing this functionality, and could get away without using this - please specify them and reopen this issue, so we can clean this up.

**Comment by adadgio** [comment]
Ah, had not though about that... although 2000 characters seems quite enough for a query. I would rather have written the limit in the docs and keep a RESTarchitecture, if it was my call (for instance offest is limited to ... 1000 !), but not the query string is unlimited... hmm ;-)

The popular ElasticSearch make their queries via GET for instance... and many others. That don't seem to kill their product ;-).

Anyway i'll look into it and report.
Tks!
