### ISSUE TITLE
parse installation class push notifications

### ISSUE THREAD

**Issue by vishalmehta1991** [ParsePlatform/Parse-SDK-Android#41]
For the first time when a device is registered for push notification the _Installation class keeps a object containing the information of the device. However i deleted all the objects manually, and when i ran the registration API in android app, the object is not created. The problem exists on both AVD as well as hardware. However if I create a new AVD, which means a new piece with different ids, the object is then created.

The problem here is this is not possible with real users and hence upon deletion and re-registration a new object should be created.

Thanks in advance.
Looking forward for support

**Comment by wangmengyan95** [comment]
@vishalmehta1991 , thanks for reporting this issue. For installation, we not only save it in our backend, but also persist it in device's disk. So when you delete the installation from the dashboard, the inconsistence between the installation in our backend and in device's disk will make save fail. 
Actually this is one of our design decisions, we highly recommend you do not delete the installation manually from the dashboard unless you are sure those apps do not need the installations. For those apps whose installations have been deleted from the dashboard, their data has to be cleared from the device or they have to be re-installed in order to get installation again.

**Comment by vishalmehta1991** [comment]
That makes sense. Thank you for the support.
