### ISSUE TITLE
Android SDK network request timeout isn't normalized with Cloud Code & iOS SDK

### ISSUE THREAD

**Issue by jmfayard** [ParsePlatform/Parse-SDK-Android#416]
Say you have a cloud function that bill your customer. If by bad luck it takes more than 10s to complete, your customer will be billed many times because the Android SDK (but not the JS or iOS SDK) replays the cloud function request.

This issue has been raised before
https://github.com/ParsePlatform/Parse-SDK-Android/issues/224
https://github.com/ParsePlatform/Parse-SDK-Android/issues/367

I am able to reproduce it reliably by creating a cloud function that waits a given timeout before completing

```
// pseudo code
 Parse.Cloud.define("test", function (request, response) {
      hasParam: timeout (in miliseconds)
      log("waiting $timeout miliseconds")
      wait($timeout)
      log("completed after $timeout miliseconds")
      response.success()
}

// real code
https://gist.github.com/jmfayard/5e866c6b9a6f12902692      
```

If I call my function in a javascript console, I have the expected behavior

```
JS console> Parse.Cloud.run("test", { timeout: 14000}).then(success, error)
JS result>     "completed after 14000 miliseconds"
Parse logs>  I2016-03-10T10:48:49.292Z] (test) waiting 14000 miliseconds
Parse logs>  I2016-03-10T10:49:03.297Z] (test) completed after 14000 miliseconds

JS console> Parse.Cloud.run("test", { timeout: 18000}).then(success, error)
JS result>     error = "Execution timed out"
Parse logs>  I2016-03-10T10:49:08.416Z] (test) waiting 18000 miliseconds
```

If I do the same thing on Android

```
public class ParseCloudFunctionsPlugin extends StethoPlugin {
        //...
        out.printf("Testing timeout: 2seconds, 13 seconds, 23seconds!");
        tryCallingCloudunction(functions.test(2000));
        tryCallingCloudunction(functions.test(13000));
        tryCallingCloudunction(functions.test(23000));
}
```

Here the parse logs show me

```
I2016-03-10T10:30:34.926Z] (test) waiting 2000 miliseconds
I2016-03-10T10:30:36.927Z] (test) completed after 2000 miliseconds

I2016-03-10T10:30:37.153Z] (test) waiting 13000 miliseconds
I2016-03-10T10:30:49.461Z] (test) waiting 13000 miliseconds
I2016-03-10T10:30:50.153Z] (test) completed after 13000 miliseconds
I2016-03-10T10:31:02.461Z] (test) completed after 13000 miliseconds
I2016-03-10T10:31:03.328Z] (test) waiting 13000 miliseconds
I2016-03-10T10:31:16.328Z] (test) completed after 13000 miliseconds
I2016-03-10T10:31:24.106Z] (test) waiting 13000 miliseconds
I2016-03-10T10:31:37.106Z] (test) completed after 13000 miliseconds
I2016-03-10T10:31:49.188Z] (test) waiting 13000 miliseconds
I2016-03-10T10:32:02.198Z] (test) completed after 13000 miliseconds

I2016-03-10T10:31:59.586Z] (test) waiting 23000 miliseconds
I2016-03-10T10:32:11.062Z] (test) waiting 23000 miliseconds
I2016-03-10T10:32:23.422Z] (test) waiting 23000 miliseconds
I2016-03-10T10:32:37.898Z] (test) waiting 23000 miliseconds
I2016-03-10T10:32:56.319Z] (test) waiting 23000 miliseconds
```

**Comment by grantland** [comment]
It would be a great contribution to the SDK to normalize the various platforms to utilize the same timeouts!

**Comment by jmfayard** [comment]
@grantland well, we do have a fix where we override by reflexion the timeout of the ParseHttpClient to 30s. 
Problem is that's fine for Cloud Functions where we absolutely don't want the same side effect to be done 5 times, but that's bad for `save()` operations where this replay is a good thing (since if the first .save() actually worked, the following .save() calls will be no ops).

**Comment by grantland** [comment]
Unfortunately Cloud Code retries are working as expected and we don't have plans to be able to modify retry logic of specific network requests.

This issue will remain open if someone wants to update the timeout duration to match our other platforms.

**Comment by jmfayard** [comment]
It's a strange expectation frankly. 
So an app asks the SDK to make a side effect.
Behind the scenes, the SDK make most of the time one side effect so during development, everything looks fine.
But sometimes, the SDK chooses instead to do behind the scenes 5 side effects.
From the perspective of the app, everything looks allright.
From the perspective of the server, everything looks like 5 legitimate independant requests for doing a side effects.

**Comment by allanascano-otus** [comment]
Im using MailGun for sending transactional emails. But since I migrated my app to AWS, the cloud code function for sending email gets called 5 times. But all those 5 calls gets completed. So I get 5 emails. I never had this problem before when I was using the parse platform. Should I stop using cloud code to send emails and just do it on the app itself? I dont know why the same cloud code function that completes under 10 secs in parse platform now takes more than 10 secs when deployed in AWS....

**Comment by allanascano-otus** [comment]
here is the log from AWS

at the start of the cloud function I print the time:
**sendEmail Mon May 16 2016 04:30:39 GMT+0000 (UTC)**

end of the function:
**email sent to XXX@gmail.com Mon May 16 2016 04:30:39 GMT+0000 (UTC)**

the function completed in just milleseconds...so why do I have 5 sets of this on my log?

**Comment by Ishimilated** [comment]
I have the same problem, sometimes cloud functions get called multiple times. Since the time limit for cloud functions is 15 seconds, it makes no sense to retry a request after only 10 seconds.

For testing purposes I wrote a function which completes in 14 seconds. If it gets called from iOS, it only gets called once and it works as expected. If it gets called from Android though, it got called more than 50 times!

It seems that there are 2 separate retry parts:
 - one within the ParseHttpClient (this retry logic is not so obvious, because the Parse network interceptor doesn't show it and even programs like Fiddler can't see multiple requests, it seems like only one request gets sent),
 - one in the ParseRequest class, which actually sends a new request (with a new Request-Id), each time after a longer delay

After disabling retries in the ParseRequest class (by setting maxRetries = 0) the 14 second long cloud function still gets called 17 times (once every 10-13 seconds).

Why isn't just one retry logic enough?

I think a good solution would be setting the timeout for the ParseHttpClient to 20 seconds (since the cloud function operation limit is 15 seconds) and limiting retries in the ParseRequest class (maybe just one retry). It makes no sense retrying for a very long time, I think users would rather see an error and try tapping again, instead of waiting for minutes. My only concern are saveEventually functions, would that affect them?

**Comment by grantland** [comment]
The request retry logic will not be changed, but we will gladly accept PRs for normalizing the timeout duration.

**Comment by chandanthakur** [comment]
We also need some sort of configuration to control this behavior. We see so many side effects on slow connections. Along with this it impacts debugging a lot as well. We just can't put break on server while app is waiting for request to be fulfilled. We see flurry of requests following up the break points.
