### ISSUE TITLE
RxJava Support

### ISSUE THREAD

**Issue by BraunreutherA** [ParsePlatform/Parse-SDK-Android#457]
Would it be an option to provide RxJava support? Out there is https://github.com/yongjhih/RxParse but it would be really nice to have this directly in the main sdk.

**Comment by grantland** [comment]
This is highly unlikely, since doing so will cause a hard dependency on RxJava which would complicate things for developers who do not wish to use RxJava and will be forced to do so.

**Comment by BraunreutherA** [comment]
It's not to make it mandatory for the user, more as an optional feature. It's like retrofit provides callbacks and Observables.

**Comment by grantland** [comment]
If done similarly to how it's done in Retrofit, we'd gladly accept a PR, but it's not a priority for us to implement.

**Comment by BraunreutherA** [comment]
Okay keep the issue open I'll work on it. Just need some review.

**Comment by grantland** [comment]
Sounds good! Might be good to discuss implementation details first, so that we can agree on the direction before diving into implementation.

**Comment by BraunreutherA** [comment]
I would do it in a similar aproach as [this library](https://github.com/yongjhih/RxParse/blob/master/rxparse/src/main/java/rx/parse/ParseObservable.java) does. 

```java
public class ParseObservable {

    public static <R extends ParseObject> Observable<R> find(ParseQuery<R> query) {
      ...
    }
}

// use like this:

Observable<ParseUser> users = ParseObservable.find(ParseUser.getQuery());
users.subscribe(user -> System.out.println(user.getObjectId()));
```

**Comment by BraunreutherA** [comment]
When I think about this, personally the second option would be the better one I think.

**Comment by BraunreutherA** [comment]
Operations Todo on query would be:
- findInBackground
- getInBackground
- firstInBackground
- countInBackground

**Comment by BraunreutherA** [comment]
Another option would be to extend the `Task<TResult>` in the Bolts Framework and add a function `asObservable()` so the excution would look like this:

``` java
ParseQuery<ParseObject> query = ParseQuery.getQuery("GameScore");
query
    .findInBackground()
    .asObservable()
    .subscribeOn(Schedulers.io()) // use your own scheduler etc...
    .subscribe(new Subscriber() {
        ...
    });
```

@grantland Do have an opinion towards this?

**Comment by BraunreutherA** [comment]
I created a PR at https://github.com/BoltsFramework/Bolts-Android/pull/121

Could you please review it? @grantland

**Comment by grantland** [comment]
https://github.com/BoltsFramework/Bolts-Android/pull/121 Adds RxJava as a hard dependency to Bolts-Android, which will transitively cause RxJava to be a hard dependency to Parse-SDK-Android.

Would you be able to explain why you'd want RxJava support? Parse doesn't supply any responses in stream format, which is one reason why we use and expose the Task pattern instead of the Observable pattern as Tasks are asynchronous single results and Observables are asynchronous streams of results.

If you're looking to easily integrate Parse with your RxJava streams, it might be better to implement [TaskObservableExtensions](https://msdn.microsoft.com/en-us/library/system.reactive.threading.tasks.taskobservableextensions(v=vs.103).aspx) to easily convert between Task and Observables externally to both libraries to prevent any additional hard dependencies.

**Comment by BraunreutherA** [comment]
Hi, thanks for the review. I think RxJava adds a nice unified interface for network calls. If there are for example calls that are giving a stream response it's nice to have every response as observable, especially with the new single and completable options.

I implemented my own layer now so I think you can cloase the issue. Thanks!

**Comment by grantland** [comment]
Normal network calls are asynchronous single results, which is why we chose to use the `Task` pattern over the `Observable` pattern.

Since you've resolved this on your own, I'll be closing this task.
