### ISSUE TITLE
Occasionally it is very slow to query from pinned data

### ISSUE THREAD

**Issue by jyoungrok** [ParsePlatform/Parse-SDK-Android#46]
Occasionally it is very slow to query from pinned data
I've been told that using "fromPin" instead of "fromLocalDataStore" could have performance improvement. 
However, it was very fast(0.2sec) sometimes but it was so slow(2~3sec) sometimes....
I didn't add any "where clause" like whereEqualTo, i just tried find().

Please, let me know the reason and how to solve this problem

**Comment by wangmengyan95** [comment]
Hi @jyoungrok , could you please tell us what data you save in the Local DataStore and what query you run in order to get it? In your case, a sample project or a unit test case which can repo your issues is prefect. For further questions, please follow our [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md) so we can help you with your issues. In particular:

> Details are key. The more information you provide us the easier it'll be for us to debug and the faster you'll receive a fix. Some examples of useful tidbits:

> * A description. What did you expect to happen and what actually happened? Why do you think that was wrong?
* A simple unit test that fails. Refer [here][tests-dir] for examples of existing unit tests. See our [README](README.md#usage) for how to run unit tests. You can submit a pull request with your failing unit test so that our CI verifies that the test fails.
* What version does this reproduce on? What version did it last work on?
* [Stacktrace or GTFO][stacktrace-or-gtfo]. In all honesty, full stacktraces with line numbers make a happy developer.
* Anything else you find relevant.

 [stacktrace-or-gtfo]: http://i.imgur.com/jacoj.jpg
 [tests-dir]: /Parse/src/test/java/com/parse

**Comment by jyoungrok** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

jyr3357@naver.com 님께 보내신 메일 <Re: [Parse-SDK-Android] Occasionally it is very slow to query from pinned data (#46)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
