### ISSUE TITLE
Sometimes saveEventually is not operated when network is availabe

### ISSUE THREAD

**Issue by jyoungrok** [ParsePlatform/Parse-SDK-Android#47]
I've tested if saveEventually function is called when network state is changed from unavailable to available.
Sometimes, saveEventually is called just after that time but sometimes it's not called for a long time (I waited for 10 minutes but it was not called. when i re-changed my network state, it was called...)

I think saveEventually occasionally does not recognize the change of network state.

Is there any bug??? and solution?

**Comment by wangmengyan95** [comment]
Hi @jyoungrok , could you provide us with a sample project and the detail steps to repo your issues? For further questions, please follow our [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md) so we can help you with your issues. In particular:

> Details are key. The more information you provide us the easier it'll be for us to debug and the faster you'll receive a fix. Some examples of useful tidbits:

> * A description. What did you expect to happen and what actually happened? Why do you think that was wrong?
* A simple unit test that fails. Refer [here][tests-dir] for examples of existing unit tests. See our [README](README.md#usage) for how to run unit tests. You can submit a pull request with your failing unit test so that our CI verifies that the test fails.
* What version does this reproduce on? What version did it last work on?
* [Stacktrace or GTFO][stacktrace-or-gtfo]. In all honesty, full stacktraces with line numbers make a happy developer.
* Anything else you find relevant.

 [stacktrace-or-gtfo]: http://i.imgur.com/jacoj.jpg
 [tests-dir]: /Parse/src/test/java/com/parse

**Comment by jyoungrok** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

jyr3357@naver.com 님께 보내신 메일 <Re: [Parse-SDK-Android] Sometimes saveEventually is not operated when network is availabe (#47)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by chitra8** [comment]
Facing the similar issue, saveEventually no saving data after connecting with network but if i changes to save its working
