### ISSUE TITLE
Parse-sdk not working with paypal-sdk

### ISSUE THREAD

**Issue by linkstatic12** [ParsePlatform/Parse-SDK-Android#511]
So I have an app which needs both paypal and parse sdk. I am using 
`
compile 'com.paypal.sdk:paypal-android-sdk:2.13.2'
compile 'com.parse:parse-android:1.13.1' 
`

When the paypal sdk is there I get this error

D/GCM: com.parse.ParseException: java.lang.NullPointerException: value == null, the code is as under

` Parse.initialize(new Parse.Configuration.Builder(getApplicationContext())
                .applicationId("CardsRUs")
                .server("http://192.168.2.93:1337/parse")   // '/' important after 2'parse'
                .build());

        ParseObject testObject = new ParseObject("TestObject");
        testObject.put("foo", "bar");
        testObject.saveInBackground (new SaveCallback() {
            public void done(ParseException e) {

                if (e != null) {
                    Log.d("GCM",e.toString());
                }
                else
                    Log.d("GCM","SEEEEEEEEEEEEEE");
            }
        });
        testObject.saveInBackground();`

When I remove the paypal sdk the problem is gone. Any Ideas?

**Comment by gouravd** [comment]
I have the exact same problem. The issue goes away when I remove the paypal sdk. Otherwise even simple operations like ParseAnonymousUtils.logIn fail with "NullPointerException value == null"

Repro:
1) Add Paypal SDK for Android
    compile('com.paypal.sdk:paypal-android-sdk:2.14.4') {
        exclude group: 'io.card'
    }

2) All Parse operations fail

**Comment by linkstatic12** [comment]
If u lower ur paypal sdk parse starts to work

**Comment by linkstatic12** [comment]
compile 'com.android.support:appcompat-v7:24.0.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha1'
    compile 'com.android.support:support-v4:24.0.0'
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    compile 'com.android.support:design:24.0.0-alpha2'
    compile 'com.onesignal:OneSignal:3.+@aar'
    compile 'com.google.android.gms:play-services-gcm:9.4.0'
    compile 'com.iangclifton.android:floatlabel:1.0.4'
    compile 'com.github.florent37:materialtextfield:1.0.5'
    compile 'com.android.volley:volley:1.0.0'
    compile 'com.paypal.sdk:paypal-android-sdk:2.12.2'
    compile 'com.parse.bolts:bolts-android:1.+'
    compile 'com.parse:parse-android:1.+'
    testCompile 'junit:junit:4.12'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.2'
    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support:support-annotations:24.0.0'
    compile 'com.google.android.gms:play-services-location:+'

**Comment by gouravd** [comment]
I found this issue show up with another library - https://github.com/javiersantos/AppUpdater

My intuition was that OKHTTP3 was somehow causing this. So when I removed the OKHTTP3 dependency from the library AppUpdater, parse worked fine.

To reconfirm if its indeed OKHTTP3, I removed all dependencies and just added OKHTTP3 3.4.1 . That reproduced the issue as well. So its not Paypal or AppUpdater, its the OKHttp3 causing this

**Comment by muetzenflo** [comment]
@gouravd Could you please post the gradle code to show how you setup you dependencies now? Did this solve the issue or was is just to confirm that okhttp is the troublemaker?

**Comment by kkgelu** [comment]
I start seeing something similar but with other SDKs/dependencies. If I isolate the ParseSDK to a separate project, it works. 

The problem is my project is having too many dependencies (~20), I have no idea Parse is not playing well with which one. Basically the whole Parse SDK fails on every operation, query, cloud functions.. nothing works

The strangest of all is I have not touched the project for about a month, it start happening all the sudden.

**Comment by gouravd** [comment]
That was to confirm that okhttp and parse not playing well together

On Jan 17, 2017 18:15, "muetzenflo" <notifications@github.com> wrote:

@gouravd <https://github.com/gouravd> Could you please post the gradle code
to show how you setup you dependencies now? Did this solve the issue or was
is just to confirm that okhttp is the troublemaker?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ParsePlatform/Parse-SDK-Android/issues/511#issuecomment-273135069>,
or mute the thread
