### ISSUE TITLE
HostnameVerifier unsafe implementation

### ISSUE THREAD

**Issue by kunalseedoc** [ParsePlatform/Parse-SDK-Android#551]
HostnameVerifier implementation in parse sdk classes resulting in security exception in play store 

"Your app is using an unsafe implementation of HostnameVerifier. Please see this Google Help Center article for details, including the deadline for fixing the vulnerability."

https://support.google.com/faqs/answer/7188426

**Comment by danielsanfr** [comment]
This is worrying! Someone has to fix this.

**Comment by Jawnnypoo** [comment]
My guess is that the blame falls on the ParseApacheHttpClient, which should probably just be removed altogether, since there is an OkHttp 3 implementation already in the SDK and just force the dependency. Apache Http was completely removed in API 23, so you are already going to have issues compiling against it.

**Comment by Jawnnypoo** [comment]
@kunalseedoc Can you confirm that this originates from Parse and is not possibly coming from another 3rd party library, such as an analytics library?

**Comment by rogerhu** [comment]
Closing unless there is any further issues.
