### ISSUE TITLE
pinInBackground function not working after query from server

### ISSUE THREAD

**Issue by KejunTong2015** [ParsePlatform/Parse-SDK-Android#68]
I am using Parse with the local datastore in my Android project, and I have met a problem when saving an object locally. The object saved on the server has pointers pointing to other objects. When I query the objects, the data is successfully retrieved. However, the pinInBackground() method seems not working after the query. The SaveCallback never gets called back. 

Example Code:

       ParseQuery<ParseObject> query = ParseQuery.getQuery("MyClass");
       query.findInBackground(new FindCallback<ParseObject>() {
           @Override
           public void done(List<ParseObject> list, ParseException e) {
               for (ParseObject object : list){

                   System.out.println("get object: " + object.getObjectId());

                   object.pinInBackground(new SaveCallback() {
                       @Override
                       public void done(ParseException e) {
                           if (e == null) {
                               System.out.println("pin successful");
                           } else {
                               System.out.println("pin error: " + e);
                           }
                       }
                   });

               }
           }
       });

Is this a known issue? How should I go about debugging this or getting more diagnostic information?

**Comment by grantland** [comment]
This is not a known issue. 

The best way to help us debug this issue is to submit a failing test case along with a thread dump since this seems to be a deadlock. You can find more information in our [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md).

To get the thread dump, you can run your code in debug mode from Android Studio and click "Pause" when you think it has deadlocked. After, you can use "Get Thread Dump" and attach the thread dump to this report.

**Comment by KejunTong2015** [comment]
Thanks for the reply! I met the problem when I was using Parse SDK version 1.9.4. Now I changed to the latest version 1.10.1, and it seems working correctly.

**Comment by grantland** [comment]
Awesome to hear! I'll be closing this issue since it has been resolved.
