### ISSUE TITLE
JSONObject field does not get updated

### ISSUE THREAD

**Issue by tvkkpt** [ParsePlatform/Parse-SDK-Android#81]
If I update a JSONObject field of an Object in Data Browser **while opening the app** and then requerying from network that object, the JSONObject field does not get updated as expected. Other field types get updated properly, only JSONObject and JSONArray don't. I must terminate the process and reopen the app to have those fields updated.

Also using Charles for proxy debugging, the response data from Parse server is totally correct, hence, I think this is a Parse Android SDK's bug.

**Comment by grantland** [comment]
This is currently working as intended and a side affect of the feature described in #58. A good workaround would be to use `getMap()` and `getList()` for now, which is the recommended route anyway since they are strongly typed.

Right now we auto-convert Dictionaries and Arrays from the server to `Map`s and `List`s. When you call `getJSONObject()` or `getJSONArray()` we convert the `Map` to`JSONObject` and `List` to `JSONArray`, but we have to call `put(String, Object)` with the `JSONObject` or `JSONArray` so that we can keep track of any changes you do to that object.

If we decide to remove this feature, we would be able to just update the value in `estimatedData` since we wouldn't have to keep track of any changes to the `JSONObject` or `JSONArray`. It'd be great to hear any input you have on the proposal so we know that we're going in the right direction with it.

**Comment by tvkkpt** [comment]
Hi @grantland. Even I've changed to use getMap() instead of getJSONObject(), those fields are still not updated.

**Comment by grantland** [comment]
Have you tried a complete uninstall/reinstall? If the problem still persists, I'd need to you provide a complete bug report which is outlined in our [Contributing Guidelines](https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/CONTRIBUTING.md).
