### ISSUE TITLE
There's 359 installation with no deviceToken

### ISSUE THREAD

**Issue by dominicsavb** [ParsePlatform/Parse-SDK-Android#90]
There's 359 installation with no deviceToken. 

What's wrong with this issue?

How to solve this problem? 

Thank you

**Comment by dominicsavb** [comment]
I already use newest SDK 1.10.1. there is 1 from 11 which has deviceToken.....

Thank you

**Comment by dominicsavb** [comment]
Btw, 

what is deviceToken use for?

**Comment by wangmengyan95** [comment]
Hi @dominicsavb , we use google GCM to send push notification to your device. DeviceToken is the identifier of your device on GCM, so your device must have the deviceToken in order to receive push notification. 
For your case, could you provide us with the following information:
1. You test environment, emulator or a actual device

2. Enable logging in our SDK with Parse.setLogLevel(Log.VERBOSE) and paste the logcat.

3. Your entire AndroidManifest.xml with any private information removed.

Thanks

**Comment by dominicsavb** [comment]
I test parse on real device... already has 21k installation... and there is a weird... there are 2 installation....
both of them are same kind of phone.. both of them without deviceToken... but... one of them can get my notification..... what's wrong with this.... so weird....

**Comment by dominicsavb** [comment]
My app is just like tutorial in http://www.androidhive.info/2015/06/android-push-notifications-using-parse-com/

Thank you

**Comment by wangmengyan95** [comment]
Hi @dominicsavb , thanks for your reply, could you enable logging in our SDK with Parse.setLogLevel(Log.VERBOSE) and paste the logcat. BTW, since you open a new issue about xiaomi phone, I guess you may test your app from China. If so, we want to say GCM service is unstable in China, so it is possible your phone can't get the `deviceToken` from GCM so the column is missing in our dashboard.
